version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        USERNAME: $USER
        USER_UID: $USER_UID
        USER_GID: $USER_GID
        DOCKER_GID: $DOCKER_GID
    cap_add:
      - SYS_PTRACE
    shm_size: 2GB
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: sleep infinity
